- hosts: localhost
  become: true
  tasks:
    - name: Pull latest Docker image
      docker_image:
        name: sassy2341/scientific-calculator
        source: pull

    - name: Run container
      docker_container:
        name: scientific-calculator
        image: sassy2341/scientific-calculator:latest
        state: started
        restart_policy: always
        tty: yes
        interactive: yes
